### ISSUE TITLE
does work with xbox one controller with some issues 

### ISSUE THREAD

**Issue by Quinnplaysgamestv** [MrCrayfish/Controllable#10]
this is copied from the curse project page (comment by spyeedy)

This mod supports Xbox One Controller with the Xbox Wireless Adapter! (I suspect it's the work of the Gamepad library, but :shrug: ).

 

I'm not too sure if it's a bug, but there's camera and/or player movement even tho the thumbsticks aren't moved. But when I move the thumbsticks slightly, it stops this movement.

 

Also, I'm not sure if it's intentional, but i'm unable to bring up the pause menu.

 

As for the icons, I feel that the icons should change depending on the controller connected/selected, as the Xbox One and PS4 controller icons differ from each other.

 

Still, great mod nonetheless! And I tried it with Vehicle Mod, the controls were great, tho I feel that the accelerate and brake buttons should be RT (R2) and LT (L2) respectively.

 

Played with Controllable 0.3.1.

**Comment by Xominus** [comment]
I have the SAME problem I really need help with this.

**Comment by MrCrayfish** [comment]
I still need to implement a feature called deadband. Basically it means "how far do I have to move the thumbstick before it detects input". Often thumbsticks don't reset exactly to the center and that's why you get the camera movement without even touching it.

Does pressing start not bring it up? I will look into it.

Custom icons will be coming soon.

You can actually use the triggers in the Vehicle Mod. You just need to go into the config (of the Vehicle Mod) and toggle triggers on. I might make it on by default in a future update as it's more natural for controller users.

**Comment by MrCrayfish** [comment]
Download 0.4.0, this has been fixed.
