### ISSUE TITLE
Bug- Crafting issues

### ISSUE THREAD

**Issue by Spencer-Black** [MrCrayfish/Controllable#104]
Minecraft 1.16.1 and controllable 0.8.1. On the crafting recipe screen the pointer automatically snaps to the sides of the left and right buttons when trying to press them, so i have to use a mouse to press them instead, and the Quick move button doesn't work, it only picks up items.

**Comment by dlp114** [comment]
I Confirm there has been an ongoing issue in the crafting menu for the last few versions where buttons seem to "push" the cursor off of them. You can hit the buttons by grazing over them and pressing if you don't stop moving the cursor but it's hard. It's as if a function to lock the cursor on to a button is having the opposite effect and pushing it away. In 16.3 it seems to have improved from earlier versions (15.2) where it affected most buttons in the crafting menu, to now only affect the green arrow buttons that turn the pages. 
And yes, quick move is broken since 16.1. (quick move in 15.2 works for me.)
Linux Mint, DS4

**Comment by MrCrayfish** [comment]
Most of these issues are fixed in recently versions
