### ISSUE TITLE
camera controls are inverted

### ISSUE THREAD

**Issue by devontheyoutuber** [MrCrayfish/Controllable#122]
So I'm in-game and it seems like my right control stick is weirdly inverted moving the stick left and right moves my head up and down and, moving it up and down moves my head up and down. I'm using 1.12.2 version

**Comment by SimonGITHU** [comment]
Hi. I had same the issue but i "fixed" it. I was just messing around with the setting and it is quite better now i will send you screenshot of mine setting but i think it will be different on your side but you cant try it and a lot helped me chaning the Icons setting where you must set: Xbox, Playstation or Default i set it Xbox because i have Xbox Controller and it was better ( and i know that the setting just change the icons but it helped me idk why ) and i have 1.14.4 version so i think you must play on newer or latest version. Hope it will help you...
![Controllable Xbox Controller Setting](https://user-images.githubusercontent.com/74112399/101084436-3eda2f00-35ae-11eb-9804-b98eeba5900c.png)

**Comment by MrCrayfish** [comment]
I don't support the 1.12 version anymore, sorry about that.
