### ISSUE TITLE
quick move bugged?

### ISSUE THREAD

**Issue by isaacffff** [MrCrayfish/Controllable#128]
when pressing quick move on an item it will just pick up the item and not move it.

**Comment by dlp114** [comment]
Also confirm Quick-Move is broken since the changes from 15.2 to 16.1. As reported by ClaudiusMinimus, Spencer-Black and others i think. Pressing the crouch button to emulate shift key doesn't work as a workaround. 
As this is really messing up my Minecraft game, I'll figure out how to donate $150 to your site if you can fix this and the Green Arrow buttons in the crafting menu for the end of January.
Linux Mint, DS4

**Comment by MrCrayfish** [comment]
This should be fixed now! Download 0.10.0

@dlp114 ;)
