### ISSUE TITLE
Virtual mouse still does not work with optifine (0.9.1)

### ISSUE THREAD

**Issue by agentwolf88** [MrCrayfish/Controllable#136]
Virtual mouse still does not work in inventory. Mouse stay in middle of the screen in inventory. :(

**Comment by MrCrayfish** [comment]
Are you using 0.9.1?

**Comment by agentwolf88** [comment]
Yes, i use 0.9.1

**Comment by ImpSpy2** [comment]
Optifine does not actually appear to be the issue as I have tested with a clean install with only Controllable and you still cannot move items around in your inventory using the controller as the virtual mouse locks onto the mouse pointer. The only partial solution for people with a DS4 controller is to disable virtual mouse and use the touchpad for mouse navigation.

**Comment by agentwolf88** [comment]
Its a DS4 problem?

**Comment by ImpSpy2** [comment]
I don't think so, same thing happens with both Xbox 360 controller and DS4 controller. It looks like its something to do with the way Minecraft handles mouse input in menus but even when I unplug my mouse, Minecraft still assumes that a mouse is connected.

**Comment by MrCrayfish** [comment]
I'm not sure what is causing the issue. As mentioned by @ImpSpy2 it doesn't seem to be Optifine, and I've backed this up by testing it myself. I've also tested using DS4Windows (https://github.com/Ryochan7/DS4Windows) and it still doesn't happen. If anyone can give more intricate details on how to reproduce the issue, it will be appreciated.

I currently have a GLFW implementation coming soon instead of using SDL to handle controller input so this may fix the issue.

**Comment by agentwolf88** [comment]
Version 0.10.1 works fine. The only issues is that the "real" mouse cursor is not invisible.

**Comment by MrCrayfish** [comment]
@agentwolf88 For now you can turn off "Pause on Focus" (F3 + P) and then unfocus the window by clicking with your mouse somewhere else. The mouse should be out of the way from there on.

**Comment by agentwolf88** [comment]
Nice to know! Thank you!
