### ISSUE TITLE
Controller button mapping glitched

### ISSUE THREAD

**Issue by RoughKoalaa** [MrCrayfish/Controllable#147]
I use a Sony PS5 DualSense controller to play minecraft. For a very strange reason, no matter what I do, the moving (not clickable) element of the right thumbstick is permanently mapped to the left trigger (L2). I have tried resetting the mod and changing the controls + remapping the layout, no matter what I do the L2 button makes the right thumbstick move up and down. This is a bug with the most recent version on curse forge, from 2 days ago.

**Comment by MrCrayfish** [comment]
Not all controllers are supported, especially new ones or controllers that aren't designed to work on a PC. This is not a problem with Controllable and more likely a mapping database issue. You can test your controller against the mappings here: https://www.generalarcade.com/gamepadtool/

**Comment by Num1MarioFan** [comment]
> Not all controllers are supported, especially new ones or controllers that aren't designed to work on a PC. This is not a problem with Controllable and more likely a mapping database issue. You can test your controller against the mappings here: https://www.generalarcade.com/gamepadtool/

Its not a mapping error on my controller I know this because I tried it with a later version of Minecraft with Controllable and it worked, but in 1.12.2 it doesn't work, and the D-Pad isn't being picked up, and whenever I try to remap the remap screen shows up for about 1 frame, and then goes away and it gets mapped to the right thumbstick for no reason at all. I need help with this as I want to use my DualSense Controller while playing 1.12.2 because I like the old mods in 1.12.2 please fix this. oh and before you ask me to get the controllerdb.txt thing of a newer version and paste it into the old one, I already did, it didn't fix anything only notable thing it did that I could see was it changed the button prompt icons to be PlayStation, I also tried using Steam's controller mapping thing that you can do to change button mappings. and the game picked up the controller (with it's bluetooth device name being "Wireless Controller") but it wouldn't pick up the controller's inputs. Please help.
