### ISSUE TITLE
Add binding to open debug info

### ISSUE THREAD

**Issue by dude98** [MrCrayfish/Controllable#148]
it'd be nice to be able to open up the F3 menu (to view coordinates) without needing to hit a button on my keyboard or if someone's playing split screen and the controller player is lost and needs to be able to see them.

also, a virtual keyboard if possible for signs and chat would also be nice for the aforementioned reason (laziness or split screen with the other player using the keyboard)
it probably won't be easy to do, since you'd need to possibly make custom textures, but it'd be really valuable for those kinds of people.

Also, why do some bindings make a section go red when nothing else is bound to it? (left and right on dpad) i tried binding screenshot to dpad right and it just went red and essentially broke the button.
P.S: Switch pro controller works when using bluetooth, when wired windows is screwy and reads motion controls data as buttons, making the controller go crazy.

**Comment by MrCrayfish** [comment]
I can add a new binding to open the debug info.

 Virtual keyboard is something on the todo list, it might be a while before it's added.
 
 Screnshots are something that can be taken from anywhere (In-game/main menu/inventory). It's considered a universal bindings and will conflict with everything else if it has the same button assigned. The entire DPad is used to navigate the inventory and menus, so that's why binding screenshot to something on the Dpad will conflict. 

There are very limited options on a controller compared to keyboard. Even the keyboard faces the same problem once you start adding a lot of mods. There is not a lot I can do to make everything work. I could make it so screenshots only work in-game (no inventories or menus) and that would fix the issue.

**Comment by MrCrayfish** [comment]
Added binding in https://github.com/MrCrayfish/Controllable/commit/cd6f9b61d99e4ab431ae9fa93fb556aa6cb23ac2
