### ISSUE TITLE
Controllable mod bricked my xbox360 controller (across all my devices)

### ISSUE THREAD

**Issue by Napstaguy04** [MrCrayfish/Controllable#152]
I was testing my wired xbox360 controllers and while strip mining, the big x suddenly stopped shining and it kept on "mining". Disconnected and shown a prompt in-game, now when I tried reconnecting it, no longer works anymore! Reconnecting it again and windows tells me that the device is not recognized anymore. Great. And not only did it affect my laptop, but it doesn't seem to be working anymore across all of my devices. The mod had completely bricked my controller and until no solutions have been found, I may have to buy another one. Until this issue of bricking controllers have been fixed, won't be using and recommending this mod to anyone.

**Comment by Napstaguy04** [comment]
Update 2: I've tried updating the drivers and reintalling it, now the system just doesn't recognize it.

**Comment by jadenPete** [comment]
Assuming that's even possible, it would had to have been a problem with GLFW, so why not [bring it up](https://github.com/glfw/glfw/issues) with them?

**Comment by MrCrayfish** [comment]
Sorry that this has happened to your controller, however this doesn't sound like an issue with Controllable. I would need much lower level access to brick a controller. Generally the only way to really brick a controller would be disconnecting a controller during a firmware update or actually frying it with a power surge. My best guess is this is simply a driver issue but I don't have enough information yet. 

When you say _"system just doesn't recognize it"_ do you mean it doesn't show up in Device Manager on your laptop (assuming that's your main system)? If it doesn't, does it show up on other computers? Is this also the case for different USB ports? Do note that it might not be listed in "Sound, video and game controllers" so make sure you check the other categories.

If the device does show in Device Manager, perform a clean installation of the device and drivers. Uninstall the device and the drivers in Device Manager (you may need to tick a box after clicking 'Uninstall Device' to also uninstall the drivers). After unplugging and plugging the device back in, Windows should automatically install the drivers for the controller.

Assuming you have an Xbox 360 because you have the controller, can you verify that it's detected by and still works on the console?

If you have any other information, let me know as I hope to get this resolved for you (even though it's unlikely a controllable issue).

**Comment by Napstaguy04** [comment]
So I've decided to come back here again, and up to this day, my xbox controller still doesn't work, but I've come up with a conclusion that it might've not been Controllable's fault. The same thing happened earlier with my mech keyboard, only to find out it was a most likely faulty usb port. So I've decided to close this until further notice. Sorry if I sounded a little angry from my last post.
