### ISSUE TITLE
LittleTiles + Controllable conflict/crash

### ISSUE THREAD

**Issue by SlayerTheChikken** [MrCrayfish/Controllable#175]
When both LittleTiles 1.5.0-327 and Controllable 0.11.2 are both present a hard crash occurs (no actual crash log.)
[latest.log](https://github.com/MrCrayfish/Controllable/files/6235248/latest.log) line 357 is where the exception occurs, though I'm sure the rest of the log has some hints.

If you need any additional info let me know, the modpack is Tekxit 3.14 on Minecraft 1.12.2.

**Comment by JukoiDev** [comment]
I can confirm

**Comment by SlayerTheChikken** [comment]
> I can confirm

Would you be able to open an issue on the LittleTiles github and cross reference it to here? (:

**Comment by MrCrayfish** [comment]
It's simply because LittleTiles replaces sendClickToBlockController, which I target in my mod using Mixins. I would argue this is actually at fault of LittleTiles since it redirects the entire method and potentially breaks other mods, not just mine. I can see if I can add a fix but I want to move away from 1.12 since it's just annoying to switch back to old codebases and it's also no longer supported by Forge.
https://github.com/CreativeMD/LittleTiles/blob/1.12/src/main/java/com/creativemd/littletiles/LittleTilesTransformer.java#L370-L382
