### ISSUE TITLE
Xbox one controller not detected 

### ISSUE THREAD

**Issue by vkrazzi** [MrCrayfish/Controllable#178]
Neither my Xbox one wired controller or wireless controller are being detected by the mod but they are detected by steam. I had it working just fine the other day but I updated forge and it will no longer work. I tried going back into a previous forge version but it still didn’t work

**Comment by MCAlexisYT** [comment]
This is basically what makes the Controllable mod a SCAM.

**Comment by MrCrayfish** [comment]
I've written a bunch of guides on different methods of connecting your controller and troubleshooting issues. I believe it will help resolve your issue since connection issue are based on a lot of factors. While Xbox One could work fine on Windows, it may not work the same on macOS or Linux and may require extra steps.
https://mrcrayfish.gitbook.io/controllable-documentation/guides/how-to-connect-a-gamepad
