### ISSUE TITLE
[1.12.2] Incompatibility with LittleTiles

### ISSUE THREAD

**Issue by CreativeMD** [MrCrayfish/Controllable#186]
Hey there,
I'm the creator of LittleTiles and apparently there is an issue with Controllable in 1.12.2. 
LittleTiles adds an event call in `Minecraft.sendClickBlockToController()` and it looks like Controlable has a problem with that.

`[04:51:36] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Argument modifier method sendClickBlockToController(Z)Z in controllable.mixins.json:client.MinecraftMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap controllable.refmap.json`

Not sure, why your injection expects this method to return a boolean? To be honest I have no clue how to fix it, but maybe you have an idea.

In Regards
CreativeMD

**Comment by MrCrayfish** [comment]
sendClickBlockToController(Z)Z is actually the signature of my Mixin method, not sendClickBlockToController(Z)V from Minecraft class. Unfortuantely my Mixin can't find the targeted method since it's being redirected/overriden in your mod.
https://github.com/CreativeMD/LittleTiles/blob/1.12/src/main/java/com/creativemd/littletiles/LittleTilesTransformer.java#L370-L382

**Comment by CreativeMD** [comment]
Oh right can your mixin maybe also accept my redirected method call (in theory that should not make a difference)?

**Comment by CreativeMD** [comment]
is that an option? Otherwise we can also find a different solution.

**Comment by MrCrayfish** [comment]
It's possible but I am more likely to discontinue the 1.12.2 version of this mod. It's just too time consuming to maintain.

**Comment by CreativeMD** [comment]
Can relate, thanks for the answer!
