### ISSUE TITLE
Alternate Radial Navigate and Select buttons

### ISSUE THREAD

**Issue by dude98** [MrCrayfish/Controllable#195]
The current radial memu is nice, but not very configurable. It'd be nice to be able to use the left stick and an alternate button to select in the radial (like X switches from swap hands to Activate Radial)

**Comment by MrCrayfish** [comment]
You can change the select button in the bindings (it's the button to open/close the radial menu). I can add an option to switch the thumbsticks though

**Comment by dude98** [comment]
you don't get what i mean, i mean a seperate activation button, since what'd it be nice to be able to do is hit left on the dpad to open the radial, then X to select the thing i want to do.

**Comment by MrCrayfish** [comment]
I can't add an alternate select button since the radial menu is not a real GUI like the player's inventory. Adding a different select button to the one that is used to open/select it would take up another button on the controller which is already full. I did though add the option to change the thumbstick in https://github.com/MrCrayfish/Controllable/commit/34e41e37b57de31045482a508cf7633e3bca091e and you can do what you originally planned in OP but open/select radial menu would be just the swap hands button, not different buttons.
