### ISSUE TITLE
Holding Button Doesn't Work; Xaero's Minimap Mod

### ISSUE THREAD

**Issue by Atolic01** [MrCrayfish/Controllable#205]
Using Xaero's Minimap, I bind "Enlarge Map" to "X" on Xbox Controller. When the button is pressed and held, it enlarges the map for a only a quarter second. It seem the game doesn't maintain the input while I hold the button on the controller.

I attempted to see if there was a setting or config change, within MC and the files in the config folder, but I couldn't find anything to adjust.

**Comment by MrCrayfish** [comment]
This is most likely due to implementation of the input in Xaero's Minimap Mod. Unfortunately since the mod is closed source, I can't actually look at how the mod keeps the map open. I try to make Controllable compatible with most mods but unfortunately I can't fix all issues simply because it's actually the other mod. I don't expect any author to make their mod compatible with Controllable. This probably won't be fixed.
