### ISSUE TITLE
This is a SCAM.

### ISSUE THREAD

**Issue by MCAlexisYT** [MrCrayfish/Controllable#213]
Basically, there is NOTHING you can do with it. I inspected the .jar file only to find that this mod is nothing more than a placebo. Just, stick to other mods.

**Comment by MCAlexisYT** [comment]
There are some files in the jar file to make it look legitimate.

**Comment by MCAlexisYT** [comment]
AND THE MOD INTENTIONALLY MAKES THE CONTROLLER WORK INTERMITTENTLY

**Comment by MCAlexisYT** [comment]
CrayFish closed this in an attempt to hide these bad practices.

**Comment by MrCrayfish** [comment]
Yes I closed this to hide these "bad practices", not because it's an invalid issue that is clogging up legitimate issues with the mod.

**Comment by MCAlexisYT** [comment]
@MrCrayfish There are certain types of scammers that are mocking people that are exposing their tactics, which includes YOU.

**Comment by MrCrayfish** [comment]
I would love for you to personally explain your experience with the mod and clearly this issue you call a "SCAM" seems to be affecting your experience. Possibly the controller is not showing in the controller selection list in game, which could be for a few simple reasons. I am reluctant to help if a title of an issue is "This is a SCAM". Go on tell me whats wrong with the mod or continue to call the mod a "SCAM" due to your incompetence.

**Comment by PokeyManatee4** [comment]
Works Fine For Me Dork

**Comment by CaptClockobob** [comment]
What a moron.
