### ISSUE TITLE
Macbook Air M1 Big Sur 11.3 Support

### ISSUE THREAD

**Issue by tstroobosscher** [MrCrayfish/Controllable#215]
Just tried to load with Xbox series X controller and haven't had any luck.

Wireless controller pairs natively, but it seems like it isnt detected.

I can't get gamepad-tester to see it either, so possibly could be misconfiguration?

What is the status of recent macOS support?

Any help is appreciated!

**Comment by MrCrayfish** [comment]
Just to be clear, Controllable isn't a controller library. It uses another controller library to get input from controllers (GLFW). The experience of what controllers will work changes depending on operating system, drivers, and controller. All I can suggest is simply try a different controller. If the Mac OS update broke it, not much I can do since it's out of my control which controllers are supported.
