### ISSUE TITLE
Cannot mine.

### ISSUE THREAD

**Issue by ScottyE929** [MrCrayfish/Controllable#226]
I'm currently using an Xboxone controller plugged via USB and it registers holding and clicking the right trigger as only a punch

**Comment by MrCrayfish** [comment]
Sounds like the mappings in the mod are not updated. The mappings in the mod were the latest available at the time of release of that particular version of the mod. If you happen to use a version of the mod from 3 years ago, you are using mapping information from 3 years ago. I've written a guide on how to update the mappings, otherwise consider a different method of connecting your controller (see GlosSI method if on Windows, or Steam Virtual Gamepad if on Linux/macOS)
https://mrcrayfish.gitbook.io/controllable-documentation/troubleshooting/solving-incorrect-mappings
