### ISSUE TITLE
xbox elite series 2 controller

### ISSUE THREAD

**Issue by leesoonkyu** [MrCrayfish/Controllable#252]
when in chess or in inventory the default buttons don't work and its kind of glitchy to use in there to

**Comment by MrCrayfish** [comment]
Sounds like mappings are out of date. This can happen because your using a modern controller (e.g PS5) on an old version of Controllable. The PS5 mappings don't exist since they were available because it wasn't release. You can update them manually by following this guide or an easier solution is to use a modern version of Controllable (MC 1.19+)
https://mrcrayfish.gitbook.io/controllable-documentation/troubleshooting/solving-incorrect-mappings
