### ISSUE TITLE
Xbox controller won’t work on MacOS

### ISSUE THREAD

**Issue by Toby-123** [MrCrayfish/Controllable#255]
Been trying to get multiple controllers on MacOS to pop up on Controllable but none of them work regardless of connection type, USB and Bluetooth. Any ideas or some sort of setting on Mac that I'm supposed to approve for it be discoverable on Controllable?

**Comment by mrucki** [comment]
Same here, cannot see Xbox gamepad in Controllable options.
Gamepad works fine in MacOS, just not detected by Controllable

**Comment by DarkIce343** [comment]
Same with me

**Comment by TideOPL** [comment]
Bump

**Comment by MrCrayfish** [comment]
Try reading this guide on How to Connect a Gamepad. I'd recommend also trying the Linux method (Steam Virtual Gamepad) as I have had reports that it works on macOS too and would allow you to use your Xbox controller wireless (since Steam is awesome for controller support).
https://mrcrayfish.gitbook.io/controllable-documentation/guides/how-to-connect-a-gamepad
