### ISSUE TITLE
Mod won't recognize xbox controller

### ISSUE THREAD

**Issue by oliviapriefert** [MrCrayfish/Controllable#256]
Hi, the controllable mod for 1.18.1 installed fine, however it doesn't seem to be recognizing my xbox controller. I'm using a macOS Big Sur and the xbox controller model 1914, connected through bluetooth. I'm wondering if there's another step I missed??? I've looked around for answers and can't seem to find anything.

**Comment by ProjectInfinity2** [comment]
Im also using mac and I will not work

**Comment by MrCrayfish** [comment]
Pretty much the new updates of Mac have broken support for controllers in LWJGL. This is based on similar experiences reported by other users. You'll have to wait for future update where I restore support for SDL2 library but it's not guaranteed that will fix it.

**Comment by Ninja1313xxx** [comment]
my xbox controller is not working too pls help MrCrayFish

**Comment by MrCrayfish** [comment]
Try reading this guide on How to Connect a Gamepad. I'd recommend also trying the Linux method (Steam Virtual Gamepad) as I have had reports that it works on macOS too and would allow you to use your Xbox controller wireless (since Steam is awesome for controller support).
https://mrcrayfish.gitbook.io/controllable-documentation/guides/how-to-connect-a-gamepad
