### ISSUE TITLE
Nintendo Pro Controller problem (Windows 10,1.18.2)

### ISSUE THREAD

**Issue by XXBLD1029** [MrCrayfish/Controllable#282]
So when I play minecraft with my pro controller on your mod, even though it says it's connected it just won't do anything. Like I try to move my stick on the minecraft menu and it shows the cross thing but it won't move.

**Comment by MrCrayfish** [comment]
Unfortunately controller support is a little hit and miss. Problems can range from the controller not having the appropriate drivers, the operating system you use, the model of controller, etc. Generally the Xbox controller is best controller if you use Windows since it's natively supported. The Switch Pro Controller is not officially supported on PC and was never designed for it. Unfortunately there is not a lot I can do since support for controllers is determined by GLFW, the input library used in Minecraft. I suggest trying a different controller if you have another one lying around.
