### ISSUE TITLE
Game crashed when accident press LT/RT without open recipe book

### ISSUE THREAD

**Issue by luckynhoc** [MrCrayfish/Controllable#309]
Game crashed with error: java.lang.NullPointerException: Cannot read field "f_93624_" because the return value of "com.mrcrayfish.controllable.mixin.client.RecipeBookPageAccessor.getBackButton()" is null
It happened when I forgot and press LT/RT without open recipe book.

**Comment by MrCrayfish** [comment]
Are you using 1.19 and Forge 41.0.64 or above?

**Comment by luckynhoc** [comment]
I'm using 1.19 with forge 41.0.63

**Comment by jennypanighetti** [comment]
I'm getting the exact same error. :( 

forge-41.0.100, controllable-0.16.3-1.19

**Comment by jennypanighetti** [comment]
[crash-2022-07-17_17.12.26-client.txt](https://github.com/MrCrayfish/Controllable/files/9128842/crash-2022-07-17_17.12.26-client.txt)

Detailed log if it helps.

**Comment by Wh1rledPeas** [comment]
Just logged in today to report similar crash. I assume it's related.

`
java.lang.NullPointerException: Cannot read field "f_93624_" because the return value of "com.mrcrayfish.controllable.mixin.client.RecipeBookPageAccessor.getForwardButton()" is null
`

My crash occurs when you open the furnace and accidentally press the RB button on the XBOX controller.

[crash-2022-08-11_02.25.15-client.txt](https://github.com/MrCrayfish/Controllable/files/9308868/crash-2022-08-11_02.25.15-client.txt)

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/Controllable/commit/1c756f42ea297ef12b69d609812f504d5e489f10
