### ISSUE TITLE
Gamepad Issue

### ISSUE THREAD

**Issue by maddiesmoliv** [MrCrayfish/Controllable#405]
Currently I am running a Switch Pro-Controller, which connectz and workz and everything, but for some reason when I pause or use the left shoulder button to place, it double-clickz? I can record and send a video if needed, but here iz the info on what I'm runnin and stuff:

Java 1.19.3
Forge 44.1.23
Switch Pro Controller
Disabled Mouse / Keyboard (Win11 Laptop)

**Comment by MrCrayfish** [comment]
It's possible the mappings are outdated, try updating them by going into the Controllable settings menu. You should find a button there. Otherwise I recommend using a software called GlosSI, it will turn your Switch Controller into an emulated Xbox controller which will work best on Windows. You can find a guide here: https://mrcrayfish.gitbook.io/controllable-documentation/guides/how-to-connect-a-gamepad/method-2-glossi

**Comment by maddiesmoliv** [comment]
Steam crashed in big picture mode - Az I currently do not have a keyboard atm, I'll update you tomorrow after my computer diez and I am able to recharge it 👍(Unlezz there iz a way to close appz with mouse only - I forgot to put BPM into windowed mode 😅)

**Comment by maddiesmoliv** [comment]
It seems virtual mouse was the issue! Ty!
