### ISSUE TITLE
Support for non-creative flight and elevators

### ISSUE THREAD

**Issue by ClaudiusMinimus** [MrCrayfish/Controllable#97]
Could you add support for non-creative flight and elevators? It seems they both use the same actions as neither works well with controllable. Specifically, I am using the Mekanism jetpack for flight and the [OpenBlocks](https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator) elevators.

Minecraft 1.16.1
Controllable 0.8.1
Playstation DS4

Thanks again for a great mod!
CM

**Comment by Ruukas97** [comment]
It doesn't work with Iron Jetpack either. It just does a normal jump rather than flying.

**Comment by MrCrayfish** [comment]
Unfortuantely this is down to the implementation of the mod and not something that can be fixed through Controllable.

For example, Mekanism detects jumping and sneaking by checking if the key on your keyboard is pressed. This could be resolved if Mekanism used the MovementInput instance to test for jumping and sneaking, however I am not expecting them to change this.

**Comment by pupnewfster** [comment]
For reference/slightly better visibility to other people who may have subscribed to this issue but don't check back on it to see if there are any new linked issues (as that is usually just a waste of time); this has been changed (https://github.com/mekanism/Mekanism/commit/dad3bca44780e8e633cc485db5bf1881b2d44c9a) for Mekanism's jetpack for Mek 10.1 (which I hope to have released by the end of this year).

Thanks for saying what specifically would need to change for it to work MrCrayfish, as otherwise you are probably quite right that I am not sure I would have spent the time diving into how Controllable works to try and improve compat.

**Comment by MrCrayfish** [comment]
I appreciate you spending the time to make a patch. If there is any issues related to autojump, you could always test if controllable is not installed and revert to the old method of input detection. You could possibly prevent auto jump from triggering the jetpack by checking if `autoJumpTime` is not equal to zero from `ClientPlayerEntity`

Edit: Names might be different since I am still on MCP mappings for 1.16.5

**Comment by pupnewfster** [comment]
Honestly, the more I think about it the more it makes sense that auto jump *would* activate the jetpack, it is just something that *seems* kind of weird, but then again vanilla's auto jump is extremely weird anyways.
